language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}
  - pip install 'virtualenv<14.0.0' tox coveralls
  - tox -e $TOX_ENV --notest

script:
  - tox -e $TOX_ENV

after_success:
  - tox -e $TOX_ENV -- coveralls $COVERALLS_OPTION

matrix:
  fast_finish: true
  include:
    - python: "3.4"
      script: tox -e lint
      env: TOX_ENV=lint
