language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

install:
  pip install tox-travis
script:
  tox

after_success:
  - tox -e $TOX_ENV -- coveralls

matrix:
  fast_finish: true
  include:
    - python: "3.4"
      script: tox -e lint
      env: TOX_ENV=lint
